services:
    registry:
        extends:
            file: jhipster-registry/jhipster-registry.yml
            service: jhipster-registry
        container_name: abaco-registry
    postgresql:
        extends:
            file: postgresql.yml
            service: abaco-postgresql
        container_name: abaco-postgresql
    elasticsearch:
        extends:
            file: elasticsearch.yml
            service: abaco-elasticsearch
        container_name: abaco-elasticsearch
    smtp:
        extends:
            file: smtp.yml
            service: smtp
        container_name: abaco-smtp
