version: '2'
services:
    abaco-elasticsearch:
        image: elasticsearch:2.4.1
        # volumes:
        #     - ~/volumes/jhipster/abaco/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            ES_JAVA_OPTS: -Xms1g -Xmx1g -Des.cluster.name=abaco -Des.discovery.zen.minimum_master_nodes=1 -Des.discovery.zen.ping.unicast.hosts=abaco-elasticsearch -Des.index.number_of_replicas=0
