name: abaco
version: 1.0.3
appVersion: 3.1.0
description: abaco
keywords:
- ABACO
home: 
sources:
- https://gitlab.basis.com.br/basis/abaco_codigo_fonte
maintainers:
- name: Basis
  email: basis@basis.com.br
