abacoui:
  name: abaco-ui
  image:
    repository: basis-registry.basis.com.br/abaco/abaco-ui
    tag: teste
  replicaCount: 1
  ingress:
    url: "abaco.basis.com.br"
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
  ports:
    port: 80
  imagePullSecrets:
  - name: basis-registry
  proxy:
    locations:
    - abaco

abaco:
  name: abaco
  image:
    repository: basis-registry.basis.com.br/abaco/abaco
    tag: teste
  replicaCount: 1
  ports:
    port: 8080
  health:
    disabled: false
  imagePullSecrets:
  - name: basis-registry
  memory:
    min: "1024"
    max: "4096"
  resources:
    requests:
      memory: "1Gi"
      cpu: "250m"
    limits:
      memory: "4Gi"
      cpu: "1000m"
  configmap:
    spring:
      profiles:
        active: "prod,swagger"
      datasource:
        url: jdbc:postgresql://pgsql-abaco/abaco
        username: abaco
        password: abaco
      jackson:
        serialization.write_dates_as_timestamps: false
      data:
        elasticsearch:
          cluster-name: abaco
          cluster-nodes: es-abaco-tst-client:9300
